name: CI/CD

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
        matrix:
            os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Set up Env
        run: | 
          python3 -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Run unittests
        # Forma mais genérica de rodar a suite de testes
        run: python3 -m pytest tests --cov